= Leveraging Unit Testing: Recommendations for Efficient Development

During the development process, it's essential to employ effective strategies for testing and debugging to ensure the
quality and reliability of software. This page will outline how and when to leverage unit testing and local live
code deployment for efficient development and debugging while ensuring code longevity.

== Unit Test

=== *What is a Unit Test*

Unit testing involves writing and running tests to verify the correctness of individual components or units of code.
It focuses on isolating and testing specific functions, methods, or classes independently of the larger system. Unit
testing makes development more efficient by identifying issues early, promoting modular and reusable code, enabling
faster refactoring, and facilitating collaboration among developers and teams. Therefore, it is advisable to
incorporate unit tests whenever possible in the development process.

More information on unit testing within aiSSEMBLE(TM) can be found in the
xref:testing.adoc#_unit_testing_the_pipeline[Testing the
Project page of the Getting Started guide]


=== *Benefits of Unit Testing*

Unit testing offers several benefits that enhance the development process and code quality. Here, we introduce some
commonly seen examples of using unit testing to improve debugging efficiency.

1. Critical functionality and edge cases: unit tests help verify that the code behaves as expected, especially
important in edge cases or corner scenarios.
2. Refactoring: During refactoring, unit tests act as a safety net, ensuring that existing functionality is not
unintentionally altered or broken.
3. Modular components: When developing modular components or libraries that will be reused across different projects,
unit tests provide confidence in their functionality and compatibility.

Please note that while unit testing should be regarded as a fundamental practice in software development and employed
whenever possible, it can be enhanced by complementary techniques like live update. Live update provides rapid
feedback during development, facilitating faster iterations and enabling immediate visual verification of code changes.
Developers should use unit tests and live update when possible to enhance code quality and efficiency

=== *Unit Testing Examples*

==== Data access and processing
Unit testing is particularly useful in scenarios such as data access and processing
within Python pipelines. For example, consider a data processing module that handles scaling and normalization of
input features. Unit testing for this module would involve writing tests specifically targeting the scaling and
normalization functions or classes.
* Example: To ensure the functional correctness of PySpark file ingestion for structured data, we can utilize unit
tests which read a CSV file into a file store and verify that the ingestion process was successful.
** Generate a `data_ingestion.feature` file within the `pipeline_name/pyspark_file_pipeline_name/tests/features`
directory, with a path that's tailored to the specific pipeline name you've created, for creating a scenario
** Create a file named `data_ingest_steps.py` in the `pipeline_name/pyspark_file_pipeline_name/tests/features/steps
directory`( the path should be tailored to pipeline you have created). Within this file, utilize the Ingest class to
import the CSV file titled "data to ingest" into the file store. Then the unit test runs to make sure that the data
file is stored in the file store.
****
`data_ingest.feature` 
[source]
----
@data_ingest
Feature: Read a CSV file into a filestore
  Scenario: Read a CSV file into files tore
    Given Ingest csv file exist
    Then the csv file data is read into the file store
----

`data_ingest.py`
[source,python]
----
import os
from behave import given, when, then  # pylint: disable=no-name-in-module
import nose.tools as nt
from src.pyspark_file_data_ingest.step.ingest import Ingest
@given("Ingest csv file exist")
def step_impl(context):
    return
@then("the csv file data is read into the file store")
def step_impl(context):
    container_name = "movie-data"
    data_folder = os.getcwd()
    file_name = "data-to-ingest.csv"
    file_path = data_folder + "/" + file_name
    context.ingest = Ingest()
    context.file_store = context.ingest.file_stores["LocalTest"]
    if not os.path.exists(container_name):
        os.makedirs(container_name)
    context.container = context.file_store.get_container(container_name=container_name)
    context.file_store.upload_object(file_path, context.container, file_name)
    context.ingest.execute_step()
    dataframe = context.test_spark_session.sql(
        """
    SELECT _c0 as title, _c1 as year, _c2 as certificate, _c3 as duration, _c4 as genre, _c5 as rating,
    _c6 as description, _c7 as stars, _c8 as votes from netflix_movies"""
    )
    dataframe.collect()
    nt.ok_(dataframe)
----
****

==== API calls and connection
If your Python pipeline interacts with external APIs to fetch data or make predictions, unit tests can be employed to
validate the API integration. This includes testing the request and response handling, verifying the correctness of
data mapping, or parsing, and ensuring the pipeline behaves as expected when interacting with different API endpoints
or handling different response scenarios. It's important to note that to perform unit tests rather than integration
tests, mocks should be used. Mocking allows you to simulate the behavior of external API endpoints without making real
network requests.

* Example: In an aiSSEMBLE project, if you are interested in testing the connection of a Python pipeline to a
data store using the JDBC protocol, you can employ unit tests that use mocks to verify the successful
establishment of this connection.
** Create a scenario file named `create_jdbc_connection_test.feature` in the
`pipeline_name/pipeline_name-pipelines/example-data-delivery-py-spark-pipeline/tests/features` directory. The path
should be tailored to the pipeline you've created.
** Create a python file named `create_jdbc_connection_test_steps.py` in the
`pipeline_name/pipeline_name-pipelines/example-data-delivery-py-spark-pipeline/tests/features/steps` directory. The
path should be tailored to the pipeline you've created. The unit test uses mock to simulate the return value when
the user calls the `DataFrame.write.jdbc` function.

****
`create_engine_test.feature` 
[source,python]
----
@create_engine_test
Feature: Placeholder test
  Scenario: python pipelines can be connected to data store via create_engine function
    Given Pyspark pipeline exists
    Then User can connect to data store via create_engine function
----

`create_engine_test_steps.py`
[source,python]
----
from unittest.mock import patch
from pyspark.sql import readwriter
import nose.tools as nt
@given("Pyspark pipeline exists")
def step_impl(context):
    return
@then("User can connect to data store via a jdbc connection through Spark")
@patch("pyspark.sql.readwriter.DataFrame")
def step_impl(context, mock_jdbc_reader):
    mock_jdbc_reader.jdbc = {
        "testValue": "test"
    }
    return_value = readwriter.DataFrameReader.read.jdbc(
        url="jdbc:database://database:port/databaseName",
        properties = {
            "user": "user",
            "password":"password",
            "driver": "driver"
        }
    )
    expected_return = "test"
    nt.eq_(return_value, expected_return)
----
****
