{{ if and .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default .Chart.Name }}
  {{ $otherdata := omit .Values.serviceAccount.metadata "name" "annotations" }}
  {{- range $key, $value := $otherdata }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- with .Values.serviceAccount.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}