{{- if and (eq .Values.persistentVolumeProperties.storageType "local") (.Values.persistentVolumeProperties.enabled) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: {{ .Values.persistentVolumeProperties.name }}-pv
spec:
  {{- with .Values.persistentVolumeProperties.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  capacity:
    storage: {{ .Values.persistentVolumeProperties.size | default "200Mi" }}
  hostPath:
    path: {{ .Values.persistentVolumeProperties.volumePathOnNode }}
    type: Directory
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
{{- end }}
